import {
  AlertTriangle,
  Apps,
  BadgeCheck,
  BarChart,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Building,
  CheckCircle,
  CheckShield,
  Chip,
  Cloud,
  CodeAlt,
  Cog,
  Database,
  File,
  Filter,
  Gift,
  HardDrive,
  HelpCircle,
  History,
  Home,
  Image,
  InfoCircle,
  Lock,
  NetworkChart,
  Package,
  Plus,
  Save,
  Search,
  Server,
  Shield,
  Slider,
  Star,
  Store,
  User,
  UserPlus,
  Video,
  Wallet,
  Wifi,
  Copy,
  Send,
  ArrowDownUp,
  ArrowDownCircle,
  ChevronDown,
  ChevronLeft,
  Layers,
  Key,
  Check,
} from "@boxicons/react";
import type { AppCategory } from "../types/prototype";

export const navigationIcons = {
  overview: Home,
  nodes: Server,
  marketplace: Store,
  installed: Package,
  rewards: Gift,
  activity: History,
  onboarding: BookOpen,
  settings: Cog,
} as const;

export const developerNavIcons = {
  overview: Home,
  apps: Apps,
  create: Plus,
  submissions: File,
  releases: Package,
  analytics: BarChart,
  rewards: Gift,
  organization: Building,
  team: UserPlus,
  profile: User,
  documentation: BookOpen,
  support: HelpCircle,
  settings: Cog,
  verification: BadgeCheck,
  media: Image,
  build: CodeAlt,
  briefcase: Briefcase,
} as const;

export const debuggerIcons = {
  bug: Bug,
  slider: Slider,
  apps: Apps,
} as const;

export const walletIcons = {
  wallet: Wallet,
  copy: Copy,
  send: Send,
  swap: ArrowDownUp,
  receive: ArrowDownCircle,
  stake: Layers,
  buy: Plus,
  chevron: ChevronDown,
  back: ChevronLeft,
  avatar: User,
  key: Key,
  shield: Shield,
  check: Check,
  create: Plus,
  warning: AlertTriangle,
} as const;

export const marketplaceIcons = {
  search: Search,
  filter: Filter,
  verified: BadgeCheck,
  security: CheckShield,
  warning: AlertTriangle,
  success: CheckCircle,
  info: InfoCircle,
  lock: Lock,
  star: Star,
  storage: HardDrive,
  compute: Chip,
  networking: Wifi,
  ai: Brain,
  data: Database,
  infrastructure: CodeAlt,
  media: Video,
  utility: Save,
  securityCategory: Shield,
  cloud: Cloud,
  network: NetworkChart,
} as const;

export const categoryIcons: Record<
  AppCategory,
  (typeof marketplaceIcons)[keyof typeof marketplaceIcons]
> = {
  storage: marketplaceIcons.storage,
  compute: marketplaceIcons.compute,
  networking: marketplaceIcons.networking,
  ai: marketplaceIcons.ai,
  data: marketplaceIcons.data,
  infrastructure: marketplaceIcons.infrastructure,
  security: marketplaceIcons.securityCategory,
  media: marketplaceIcons.media,
  utility: marketplaceIcons.utility,
};

export type NavigationIconKey = keyof typeof navigationIcons;
